### PR TITLE
Cleaned up

### PR DESCRIPTION
**Pull request by ghost**
Added some lines to make sure Terminal wasn't already installed. If it wasn't, then there's a check to see if BigBoss is on the user's repo list.

### CODE REVIEW

**Review by ThatNerdyPikachu — APPROVED** [review]
Love the Library remove change!

**Comment by ipadkid358** [comment]
@thebeastgamer25 Thanks! I'm a little worried about it, cause it just sorts for those keywords, but it should be fine

**Comment by nathanaccidentally** [comment]
Ah, I forgot about the Preferences folder. Need to add that too. :/

**Comment by nathanaccidentally** [comment]
I just merged this branch and will continue to test this build with only 1 or 2 testers. If it works then this should be the GM and the release should be within the next day or two.

**Comment by nathanaccidentally** [comment]
Hey ipad_kid, may I ask why you do a 'check step' and update manually instead of just running `apt-get update`?

**Comment by ipadkid358** [comment]
@nathanaccidentally Yeah, just want to check that BigBoss is a repo the user has. If they already have the BigBoss repo added, then you don't need to run apt-get update, which is a big process to run anyway

**Comment by nathanaccidentally** [comment]
Ah yeah that makes sense; thanks so much for your help. Do you have a discord? It would be great to work on potential updates and get to know each other a little better.

**Comment by ipadkid358** [comment]
@nathanaccidentally no, I don't, but I probably should, lol. My current contact methods are here: https://ipadkid358.github.io/contact.html

**Comment by nathanaccidentally** [comment]
You should ;)

**Comment by ipadkid358** [comment]
@nathanaccidentally I'm now on Discord at ipad_kid#3337

**Comment by nathanaccidentally** [comment]
Cool, I'll add you.

**Comment by ThatNerdyPikachu** [comment]
@nathanaccidentally my discord is @TheBeastGamer25#2849

I'm pretty much a discord vet, so if u need anything hmu!

**Pull request merged**
