### PR TITLE
Patched script

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nathanaccidentally** [comment]
I don't know why you closed this, but I'll leave some comments.

When you filter out folders, you didn't include carrier settings. That's all really. Plus I'm working on adding a few things to make OSRestore a little better right now so I'll take some of the other things into mind and incorporate them. I'll be sure to give you credit where it's due.

Thanks!

**Comment by ipadkid358** [comment]
@nathanaccidentally, I closed it because you had made some changes since I had forked. I have now re-patched and opened another pull request. 

What are the exact files/ directories that should should not be deleted from `/var/mobile/Library`?

**Comment by nathanaccidentally** [comment]
Carrier Bundle.Bundle (Current Carrier settings)
Carrier Bundles (Different carriers configurations)
CarrierDefault.Bundle (stock international configuracion required for activation)
Operator Bundle.Bundle Same as Carrier Bundle.bundle

**Comment by nathanaccidentally** [comment]
If you'd like to make a pull request with those that would be pretty nice.

**Pull request closed without merging**
